[package]
name = "poetry-slam"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.62"
image = {version = "0.24.3", default-features = false, features = ["png"]}
